/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrgSlugBucketNameRouteImport } from './routes/$orgSlug/bucketName'
import { Route as OrgSlugDashboardRouteImport } from './routes/$orgSlug/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugBucketNameRoute = OrgSlugBucketNameRouteImport.update({
  id: '/bucketName',
  path: '/bucketName',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugDashboardRoute = OrgSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrgSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/login': typeof LoginRoute
  '/$orgSlug/bucketName': typeof OrgSlugBucketNameRoute
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/login': typeof LoginRoute
  '/$orgSlug/bucketName': typeof OrgSlugBucketNameRoute
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/login': typeof LoginRoute
  '/$orgSlug/bucketName': typeof OrgSlugBucketNameRoute
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/login'
    | '/$orgSlug/bucketName'
    | '/$orgSlug/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug'
    | '/login'
    | '/$orgSlug/bucketName'
    | '/$orgSlug/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/login'
    | '/$orgSlug/bucketName'
    | '/$orgSlug/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/bucketName': {
      id: '/$orgSlug/bucketName'
      path: '/bucketName'
      fullPath: '/$orgSlug/bucketName'
      preLoaderRoute: typeof OrgSlugBucketNameRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/dashboard': {
      id: '/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/dashboard'
      preLoaderRoute: typeof OrgSlugDashboardRouteImport
      parentRoute: typeof OrgSlugRoute
    }
  }
}

interface OrgSlugRouteChildren {
  OrgSlugBucketNameRoute: typeof OrgSlugBucketNameRoute
  OrgSlugDashboardRoute: typeof OrgSlugDashboardRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugBucketNameRoute: OrgSlugBucketNameRoute,
  OrgSlugDashboardRoute: OrgSlugDashboardRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
